apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.flask_app.name }}
  namespace: {{ .Values.namespace}}
  labels:
    name: {{ .Values.services.flask_app.name }}
spec:
  type: NodePort
  selector:
    name: {{ .Values.services.flask_app.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.services.flask_app.service_port}}
      protocol: TCP
      name: http
